# Generated by Django 2.2 on 2019-05-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_mensagemdecontato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemdecontato',
            options={'verbose_name': 'Mensagem de contato', 'verbose_name_plural': 'Mensagens de contato'},
        ),
    ]
